name: Cypress Tests (Prod)

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cypress-run:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify your Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Cypress run (Prod)
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          run: yarn cypress run
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.PRODUCTION.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
