name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run in Prod
        uses: cypress-io/github-action@v6
        run: npx cypress run
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.CYPRESS_GITHUB_TOKEN }}
          CYPRESS_BASE_URL: https://api.realworld.io/api
          CYPRESS_PREFIX: test-prod