# name: Cypress Tests (Remote)

# on:
#   push:
#     branches:
#       - main # Trigger this workflow when changes are pushed to the main branch

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16'

#       - name: Install dependencies
#         run: npm install

#       - name: Run Cypress tests against remote API
#         run: npx cypress run
#         env:
#           CYPRESS_BASE_URL: https://api.realworld.io/api
#           CYPRESS_PREFIX: test-prod
